esphome:
  name: pump-vfd
  friendly_name: pump-vfd

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  password: "secret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  domain: .lan.domain.tld

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pump-Vfd Fallback Hotspot"
    password: "secret"

captive_portal:

web_server:
  port: 80

status_led:
  pin:
    number: GPIO2

switch:
  - platform: gpio
    pin:
      number: GPIO5
      mode: output
      inverted: false
    id: pump_vfd_switch
    name: "Pump VFD Control"
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: input_pullup
    name: "Pump VFD Button"
    on_press:
      - switch.toggle: pump_vfd_switch
      - output.turn_on: led_output
    on_release:
      - output.turn_off: led_output

  - platform: gpio
    pin:
      number: GPIO34
      mode: input
    name: "Pump VFD Active"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

output:
  - platform: gpio
    pin: GPIO2
    id: led_output
